# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.animal_wolf.root] run return 0
execute on passengers if entity @s[tag=aj.animal_wolf.data] unless data entity @s {data:{rigHash: '7193e760c079e95df93a40011bf9cdb0d9f1d6c0857729be3b29ae7049e911dd'}} on vehicle run function animated_java:animal_wolf/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1