# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.animal_alpha.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'animal_alpha', 'function_path': 'animated_java:animal_alpha/variants/default/apply'}
execute on passengers if entity @s[tag=aj.animal_alpha.bone.bone4] run function animated_java:animal_alpha/variants/default/zzz/0
execute on passengers if entity @s[tag=aj.animal_alpha.bone.bone] run function animated_java:animal_alpha/variants/default/zzz/1
execute on passengers if entity @s[tag=aj.animal_alpha.bone.bone5] run function animated_java:animal_alpha/variants/default/zzz/2
execute on passengers if entity @s[tag=aj.animal_alpha.bone.bone2] run function animated_java:animal_alpha/variants/default/zzz/3
execute on passengers if entity @s[tag=aj.animal_alpha.bone.head] run function animated_java:animal_alpha/variants/default/zzz/4
execute on passengers if entity @s[tag=aj.animal_alpha.bone.bone6] run function animated_java:animal_alpha/variants/default/zzz/5
execute on passengers if entity @s[tag=aj.animal_alpha.bone.left_down_arm] run function animated_java:animal_alpha/variants/default/zzz/6
execute on passengers if entity @s[tag=aj.animal_alpha.bone.left_upper_arm] run function animated_java:animal_alpha/variants/default/zzz/7
execute on passengers if entity @s[tag=aj.animal_alpha.bone.bone7] run function animated_java:animal_alpha/variants/default/zzz/8
execute on passengers if entity @s[tag=aj.animal_alpha.bone.left_down_arm2] run function animated_java:animal_alpha/variants/default/zzz/9
execute on passengers if entity @s[tag=aj.animal_alpha.bone.left_upper_arm2] run function animated_java:animal_alpha/variants/default/zzz/10
execute on passengers if entity @s[tag=aj.animal_alpha.bone.upperbody] run function animated_java:animal_alpha/variants/default/zzz/11
execute on passengers if entity @s[tag=aj.animal_alpha.bone.downbody] run function animated_java:animal_alpha/variants/default/zzz/12