# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_bear.node.front_leg_right_under2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_front_leg_right_under2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_bear.node.rear_leg_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_rear_leg_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_bear.node.front_leg_left_under2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_front_leg_left_under2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_bear.node.rear_leg_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_rear_leg_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_bear.node.head] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_head set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_bear.node.front_leg_left_under] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_front_leg_left_under set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_bear.node.front_leg_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_front_leg_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_bear.node.front_leg_right_under] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_front_leg_right_under set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_bear.node.front_leg_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_front_leg_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_bear.node.front_body] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_front_body set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_bear.node.rear_body] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_rear_body set from storage aj:uuid main.out