# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.animal_bear.root] run return 0
execute on passengers if entity @s[tag=aj.animal_bear.data] unless data entity @s {data:{rigHash: 'b0e34eedfbe6488ec538abe5f4007eca9c6da02b7a93b4d076ef99b4ce943f4a'}} on vehicle run function animated_java:animal_bear/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1