# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.animal_boar.root] run return 0
execute on passengers if entity @s[tag=aj.animal_boar.data] unless data entity @s {data:{rigHash: '2d24ac98bd53e4f7f64eac92fe8545640120e34af8759b9b7e91142210b8191c'}} on vehicle run function animated_java:animal_boar/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1