# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.animal_boar.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'animal_boar', 'function_path': 'animated_java:animal_boar/variants/default/apply'}
execute on passengers if entity @s[tag=aj.animal_boar.bone.rear_body] run function animated_java:animal_boar/variants/default/zzz/0
execute on passengers if entity @s[tag=aj.animal_boar.bone.head] run function animated_java:animal_boar/variants/default/zzz/1
execute on passengers if entity @s[tag=aj.animal_boar.bone.front_body] run function animated_java:animal_boar/variants/default/zzz/2
execute on passengers if entity @s[tag=aj.animal_boar.bone.front_leg_left_under] run function animated_java:animal_boar/variants/default/zzz/3
execute on passengers if entity @s[tag=aj.animal_boar.bone.front_leg_left] run function animated_java:animal_boar/variants/default/zzz/4
execute on passengers if entity @s[tag=aj.animal_boar.bone.rear_leg_right_under] run function animated_java:animal_boar/variants/default/zzz/5
execute on passengers if entity @s[tag=aj.animal_boar.bone.rear_leg_right] run function animated_java:animal_boar/variants/default/zzz/6
execute on passengers if entity @s[tag=aj.animal_boar.bone.front_leg_right_under] run function animated_java:animal_boar/variants/default/zzz/7
execute on passengers if entity @s[tag=aj.animal_boar.bone.front_leg_right] run function animated_java:animal_boar/variants/default/zzz/8
execute on passengers if entity @s[tag=aj.animal_boar.bone.right_leg_left_under] run function animated_java:animal_boar/variants/default/zzz/9
execute on passengers if entity @s[tag=aj.animal_boar.bone.right_leg_left] run function animated_java:animal_boar/variants/default/zzz/10
execute on passengers if entity @s[tag=aj.animal_boar.bone.tale] run function animated_java:animal_boar/variants/default/zzz/11