# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.animal_bear.root] run return 0
execute on passengers if entity @s[tag=aj.animal_bear.data] unless data entity @s {data:{rigHash: 'b973d382113817dc89fe235f51a9efa95d4597e56effa5399a3e68c04fcf8397'}} on vehicle run function animated_java:animal_bear/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1