# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.animal_boar.root] run return 0
execute on passengers if entity @s[tag=aj.animal_boar.data] unless data entity @s {data:{rigHash: 'ab0af64ee555f6222b6ec0ffb93f28a1aba994d72f83e2802ca27283cb5eefa5'}} on vehicle run function animated_java:animal_boar/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1