# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_alpha.node.bone4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_alpha.node.bone] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_alpha.node.bone5] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_alpha.node.bone2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_alpha.node.head] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_head set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_alpha.node.bone6] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone6 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_alpha.node.left_down_arm] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_down_arm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_alpha.node.left_upper_arm] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_upper_arm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_alpha.node.bone7] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone7 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_alpha.node.left_down_arm2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_down_arm2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_alpha.node.left_upper_arm2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_upper_arm2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_alpha.node.upperbody] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_upperbody set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_alpha.node.downbody] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_downbody set from storage aj:uuid main.out