# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_alpha.bone.bone4] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_alpha.bone.bone] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_alpha.bone.bone5] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_alpha.bone.bone2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_alpha.bone.head] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_head set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_alpha.bone.bone6] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone6 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_alpha.bone.left_down_arm] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_down_arm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_alpha.bone.left_upper_arm] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_upper_arm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_alpha.bone.bone7] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone7 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_alpha.bone.left_down_arm2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_down_arm2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_alpha.bone.left_upper_arm2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_upper_arm2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_alpha.bone.upperbody] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_upperbody set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_alpha.bone.downbody] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_downbody set from storage aj:uuid main.out