# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.animal_alpha.root] run return 0
execute on passengers if entity @s[tag=aj.animal_alpha.data] unless data entity @s {data:{rigHash: '44a83da02534aba07b44baa383293044b6b3c7752a70cc4379102f6f4d095481'}} on vehicle run function animated_java:animal_alpha/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1