# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_wolf.node.rear_leg_right_under] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_rear_leg_right_under set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_wolf.node.rear_leg_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_rear_leg_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_wolf.node.right_leg_left_under] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_leg_left_under set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_wolf.node.rear_leg_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_rear_leg_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_wolf.node.tale] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_tale set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_wolf.node.rear_body] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_rear_body set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_wolf.node.head] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_head set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_wolf.node.talon_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_talon_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_wolf.node.front_leg_left_under] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_front_leg_left_under set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_wolf.node.front_leg_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_front_leg_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_wolf.node.talon_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_talon_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_wolf.node.front_leg_right_under] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_front_leg_right_under set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_wolf.node.front_leg_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_front_leg_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.animal_wolf.node.front_body] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_front_body set from storage aj:uuid main.out