# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.animal_wolf.root] run return 0
execute on passengers if entity @s[tag=aj.animal_wolf.data] unless data entity @s {data:{rigHash: '469952ad73d9adce7151a19deb0f9c7fcbe347d625f8300f0a2a756b8c8ef6a8'}} on vehicle run function animated_java:animal_wolf/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1