# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.animal_alpha.root] run return 0
execute on passengers if entity @s[tag=aj.animal_alpha.data] unless data entity @s {data:{rigHash: 'a5083ab27cd958996180418bda405287b2cb594f14e55dbee7d7f65733694c84'}} on vehicle run function animated_java:animal_alpha/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1